<?php
/**
 * Country list for Cybercrime Support portal.
 *
 * @package NaveinTheme
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array( 'code' => 'AF', 'dial' => '+93', 'flag' => '🇦🇫', 'name' => array( 'en' => 'Afghanistan', 'de' => 'Afghanistan' ) ),
	array( 'code' => 'AL', 'dial' => '+355', 'flag' => '🇦🇱', 'name' => array( 'en' => 'Albania', 'de' => 'Albanien' ) ),
	array( 'code' => 'DZ', 'dial' => '+213', 'flag' => '🇩🇿', 'name' => array( 'en' => 'Algeria', 'de' => 'Algerien' ) ),
	array( 'code' => 'AD', 'dial' => '+376', 'flag' => '🇦🇩', 'name' => array( 'en' => 'Andorra', 'de' => 'Andorra' ) ),
	array( 'code' => 'AO', 'dial' => '+244', 'flag' => '🇦🇴', 'name' => array( 'en' => 'Angola', 'de' => 'Angola' ) ),
	array( 'code' => 'AR', 'dial' => '+54', 'flag' => '🇦🇷', 'name' => array( 'en' => 'Argentina', 'de' => 'Argentinien' ) ),
	array( 'code' => 'AM', 'dial' => '+374', 'flag' => '🇦🇲', 'name' => array( 'en' => 'Armenia', 'de' => 'Armenien' ) ),
	array( 'code' => 'AU', 'dial' => '+61', 'flag' => '🇦🇺', 'name' => array( 'en' => 'Australia', 'de' => 'Australien' ) ),
	array( 'code' => 'AT', 'dial' => '+43', 'flag' => '🇦🇹', 'name' => array( 'en' => 'Austria', 'de' => 'Österreich' ) ),
	array( 'code' => 'AZ', 'dial' => '+994', 'flag' => '🇦🇿', 'name' => array( 'en' => 'Azerbaijan', 'de' => 'Aserbaidschan' ) ),
	array( 'code' => 'BH', 'dial' => '+973', 'flag' => '🇧🇭', 'name' => array( 'en' => 'Bahrain', 'de' => 'Bahrain' ) ),
	array( 'code' => 'BD', 'dial' => '+880', 'flag' => '🇧🇩', 'name' => array( 'en' => 'Bangladesh', 'de' => 'Bangladesch' ) ),
	array( 'code' => 'BY', 'dial' => '+375', 'flag' => '🇧🇾', 'name' => array( 'en' => 'Belarus', 'de' => 'Belarus' ) ),
	array( 'code' => 'BE', 'dial' => '+32', 'flag' => '🇧🇪', 'name' => array( 'en' => 'Belgium', 'de' => 'Belgien' ) ),
	array( 'code' => 'BA', 'dial' => '+387', 'flag' => '🇧🇦', 'name' => array( 'en' => 'Bosnia and Herzegovina', 'de' => 'Bosnien und Herzegowina' ) ),
	array( 'code' => 'BR', 'dial' => '+55', 'flag' => '🇧🇷', 'name' => array( 'en' => 'Brazil', 'de' => 'Brasilien' ) ),
	array( 'code' => 'BG', 'dial' => '+359', 'flag' => '🇧🇬', 'name' => array( 'en' => 'Bulgaria', 'de' => 'Bulgarien' ) ),
	array( 'code' => 'CA', 'dial' => '+1', 'flag' => '🇨🇦', 'name' => array( 'en' => 'Canada', 'de' => 'Kanada' ) ),
	array( 'code' => 'CL', 'dial' => '+56', 'flag' => '🇨🇱', 'name' => array( 'en' => 'Chile', 'de' => 'Chile' ) ),
	array( 'code' => 'CN', 'dial' => '+86', 'flag' => '🇨🇳', 'name' => array( 'en' => 'China', 'de' => 'China' ) ),
	array( 'code' => 'CO', 'dial' => '+57', 'flag' => '🇨🇴', 'name' => array( 'en' => 'Colombia', 'de' => 'Kolumbien' ) ),
	array( 'code' => 'HR', 'dial' => '+385', 'flag' => '🇭🇷', 'name' => array( 'en' => 'Croatia', 'de' => 'Kroatien' ) ),
	array( 'code' => 'CY', 'dial' => '+357', 'flag' => '🇨🇾', 'name' => array( 'en' => 'Cyprus', 'de' => 'Zypern' ) ),
	array( 'code' => 'CZ', 'dial' => '+420', 'flag' => '🇨🇿', 'name' => array( 'en' => 'Czechia', 'de' => 'Tschechien' ) ),
	array( 'code' => 'DK', 'dial' => '+45', 'flag' => '🇩🇰', 'name' => array( 'en' => 'Denmark', 'de' => 'Dänemark' ) ),
	array( 'code' => 'EG', 'dial' => '+20', 'flag' => '🇪🇬', 'name' => array( 'en' => 'Egypt', 'de' => 'Ägypten' ) ),
	array( 'code' => 'EE', 'dial' => '+372', 'flag' => '🇪🇪', 'name' => array( 'en' => 'Estonia', 'de' => 'Estland' ) ),
	array( 'code' => 'FI', 'dial' => '+358', 'flag' => '🇫🇮', 'name' => array( 'en' => 'Finland', 'de' => 'Finnland' ) ),
	array( 'code' => 'FR', 'dial' => '+33', 'flag' => '🇫🇷', 'name' => array( 'en' => 'France', 'de' => 'Frankreich' ) ),
	array( 'code' => 'GE', 'dial' => '+995', 'flag' => '🇬🇪', 'name' => array( 'en' => 'Georgia', 'de' => 'Georgien' ) ),
	array( 'code' => 'DE', 'dial' => '+49', 'flag' => '🇩🇪', 'name' => array( 'en' => 'Germany', 'de' => 'Deutschland' ) ),
	array( 'code' => 'GR', 'dial' => '+30', 'flag' => '🇬🇷', 'name' => array( 'en' => 'Greece', 'de' => 'Griechenland' ) ),
	array( 'code' => 'HK', 'dial' => '+852', 'flag' => '🇭🇰', 'name' => array( 'en' => 'Hong Kong', 'de' => 'Hongkong' ) ),
	array( 'code' => 'HU', 'dial' => '+36', 'flag' => '🇭🇺', 'name' => array( 'en' => 'Hungary', 'de' => 'Ungarn' ) ),
	array( 'code' => 'IS', 'dial' => '+354', 'flag' => '🇮🇸', 'name' => array( 'en' => 'Iceland', 'de' => 'Island' ) ),
	array( 'code' => 'IN', 'dial' => '+91', 'flag' => '🇮🇳', 'name' => array( 'en' => 'India', 'de' => 'Indien' ) ),
	array( 'code' => 'ID', 'dial' => '+62', 'flag' => '🇮🇩', 'name' => array( 'en' => 'Indonesia', 'de' => 'Indonesien' ) ),
	array( 'code' => 'IR', 'dial' => '+98', 'flag' => '🇮🇷', 'name' => array( 'en' => 'Iran', 'de' => 'Iran' ) ),
	array( 'code' => 'IQ', 'dial' => '+964', 'flag' => '🇮🇶', 'name' => array( 'en' => 'Iraq', 'de' => 'Irak' ) ),
	array( 'code' => 'IE', 'dial' => '+353', 'flag' => '🇮🇪', 'name' => array( 'en' => 'Ireland', 'de' => 'Irland' ) ),
	array( 'code' => 'IL', 'dial' => '+972', 'flag' => '🇮🇱', 'name' => array( 'en' => 'Israel', 'de' => 'Israel' ) ),
	array( 'code' => 'IT', 'dial' => '+39', 'flag' => '🇮🇹', 'name' => array( 'en' => 'Italy', 'de' => 'Italien' ) ),
	array( 'code' => 'JP', 'dial' => '+81', 'flag' => '🇯🇵', 'name' => array( 'en' => 'Japan', 'de' => 'Japan' ) ),
	array( 'code' => 'JO', 'dial' => '+962', 'flag' => '🇯🇴', 'name' => array( 'en' => 'Jordan', 'de' => 'Jordanien' ) ),
	array( 'code' => 'KZ', 'dial' => '+7', 'flag' => '🇰🇿', 'name' => array( 'en' => 'Kazakhstan', 'de' => 'Kasachstan' ) ),
	array( 'code' => 'KE', 'dial' => '+254', 'flag' => '🇰🇪', 'name' => array( 'en' => 'Kenya', 'de' => 'Kenia' ) ),
	array( 'code' => 'KW', 'dial' => '+965', 'flag' => '🇰🇼', 'name' => array( 'en' => 'Kuwait', 'de' => 'Kuwait' ) ),
	array( 'code' => 'LV', 'dial' => '+371', 'flag' => '🇱🇻', 'name' => array( 'en' => 'Latvia', 'de' => 'Lettland' ) ),
	array( 'code' => 'LB', 'dial' => '+961', 'flag' => '🇱🇧', 'name' => array( 'en' => 'Lebanon', 'de' => 'Libanon' ) ),
	array( 'code' => 'LY', 'dial' => '+218', 'flag' => '🇱🇾', 'name' => array( 'en' => 'Libya', 'de' => 'Libyen' ) ),
	array( 'code' => 'LT', 'dial' => '+370', 'flag' => '🇱🇹', 'name' => array( 'en' => 'Lithuania', 'de' => 'Litauen' ) ),
	array( 'code' => 'LU', 'dial' => '+352', 'flag' => '🇱🇺', 'name' => array( 'en' => 'Luxembourg', 'de' => 'Luxemburg' ) ),
	array( 'code' => 'MY', 'dial' => '+60', 'flag' => '🇲🇾', 'name' => array( 'en' => 'Malaysia', 'de' => 'Malaysia' ) ),
	array( 'code' => 'MT', 'dial' => '+356', 'flag' => '🇲🇹', 'name' => array( 'en' => 'Malta', 'de' => 'Malta' ) ),
	array( 'code' => 'MX', 'dial' => '+52', 'flag' => '🇲🇽', 'name' => array( 'en' => 'Mexico', 'de' => 'Mexiko' ) ),
	array( 'code' => 'MD', 'dial' => '+373', 'flag' => '🇲🇩', 'name' => array( 'en' => 'Moldova', 'de' => 'Moldau' ) ),
	array( 'code' => 'MA', 'dial' => '+212', 'flag' => '🇲🇦', 'name' => array( 'en' => 'Morocco', 'de' => 'Marokko' ) ),
	array( 'code' => 'NL', 'dial' => '+31', 'flag' => '🇳🇱', 'name' => array( 'en' => 'Netherlands', 'de' => 'Niederlande' ) ),
	array( 'code' => 'NZ', 'dial' => '+64', 'flag' => '🇳🇿', 'name' => array( 'en' => 'New Zealand', 'de' => 'Neuseeland' ) ),
	array( 'code' => 'NG', 'dial' => '+234', 'flag' => '🇳🇬', 'name' => array( 'en' => 'Nigeria', 'de' => 'Nigeria' ) ),
	array( 'code' => 'MK', 'dial' => '+389', 'flag' => '🇲🇰', 'name' => array( 'en' => 'North Macedonia', 'de' => 'Nordmazedonien' ) ),
	array( 'code' => 'NO', 'dial' => '+47', 'flag' => '🇳🇴', 'name' => array( 'en' => 'Norway', 'de' => 'Norwegen' ) ),
	array( 'code' => 'OM', 'dial' => '+968', 'flag' => '🇴🇲', 'name' => array( 'en' => 'Oman', 'de' => 'Oman' ) ),
	array( 'code' => 'PK', 'dial' => '+92', 'flag' => '🇵🇰', 'name' => array( 'en' => 'Pakistan', 'de' => 'Pakistan' ) ),
	array( 'code' => 'PS', 'dial' => '+970', 'flag' => '🇵🇸', 'name' => array( 'en' => 'Palestine', 'de' => 'Palästina' ) ),
	array( 'code' => 'PE', 'dial' => '+51', 'flag' => '🇵🇪', 'name' => array( 'en' => 'Peru', 'de' => 'Peru' ) ),
	array( 'code' => 'PH', 'dial' => '+63', 'flag' => '🇵🇭', 'name' => array( 'en' => 'Philippines', 'de' => 'Philippinen' ) ),
	array( 'code' => 'PL', 'dial' => '+48', 'flag' => '🇵🇱', 'name' => array( 'en' => 'Poland', 'de' => 'Polen' ) ),
	array( 'code' => 'PT', 'dial' => '+351', 'flag' => '🇵🇹', 'name' => array( 'en' => 'Portugal', 'de' => 'Portugal' ) ),
	array( 'code' => 'QA', 'dial' => '+974', 'flag' => '🇶🇦', 'name' => array( 'en' => 'Qatar', 'de' => 'Katar' ) ),
	array( 'code' => 'RO', 'dial' => '+40', 'flag' => '🇷🇴', 'name' => array( 'en' => 'Romania', 'de' => 'Rumänien' ) ),
	array( 'code' => 'RU', 'dial' => '+7', 'flag' => '🇷🇺', 'name' => array( 'en' => 'Russia', 'de' => 'Russland' ) ),
	array( 'code' => 'SA', 'dial' => '+966', 'flag' => '🇸🇦', 'name' => array( 'en' => 'Saudi Arabia', 'de' => 'Saudi-Arabien' ) ),
	array( 'code' => 'RS', 'dial' => '+381', 'flag' => '🇷🇸', 'name' => array( 'en' => 'Serbia', 'de' => 'Serbien' ) ),
	array( 'code' => 'SG', 'dial' => '+65', 'flag' => '🇸🇬', 'name' => array( 'en' => 'Singapore', 'de' => 'Singapur' ) ),
	array( 'code' => 'SK', 'dial' => '+421', 'flag' => '🇸🇰', 'name' => array( 'en' => 'Slovakia', 'de' => 'Slowakei' ) ),
	array( 'code' => 'SI', 'dial' => '+386', 'flag' => '🇸🇮', 'name' => array( 'en' => 'Slovenia', 'de' => 'Slowenien' ) ),
	array( 'code' => 'ZA', 'dial' => '+27', 'flag' => '🇿🇦', 'name' => array( 'en' => 'South Africa', 'de' => 'Südafrika' ) ),
	array( 'code' => 'KR', 'dial' => '+82', 'flag' => '🇰🇷', 'name' => array( 'en' => 'South Korea', 'de' => 'Südkorea' ) ),
	array( 'code' => 'ES', 'dial' => '+34', 'flag' => '🇪🇸', 'name' => array( 'en' => 'Spain', 'de' => 'Spanien' ) ),
	array( 'code' => 'SE', 'dial' => '+46', 'flag' => '🇸🇪', 'name' => array( 'en' => 'Sweden', 'de' => 'Schweden' ) ),
	array( 'code' => 'CH', 'dial' => '+41', 'flag' => '🇨🇭', 'name' => array( 'en' => 'Switzerland', 'de' => 'Schweiz' ) ),
	array( 'code' => 'SY', 'dial' => '+963', 'flag' => '🇸🇾', 'name' => array( 'en' => 'Syria', 'de' => 'Syrien' ) ),
	array( 'code' => 'TW', 'dial' => '+886', 'flag' => '🇹🇼', 'name' => array( 'en' => 'Taiwan', 'de' => 'Taiwan' ) ),
	array( 'code' => 'TH', 'dial' => '+66', 'flag' => '🇹🇭', 'name' => array( 'en' => 'Thailand', 'de' => 'Thailand' ) ),
	array( 'code' => 'TN', 'dial' => '+216', 'flag' => '🇹🇳', 'name' => array( 'en' => 'Tunisia', 'de' => 'Tunesien' ) ),
	array( 'code' => 'TR', 'dial' => '+90', 'flag' => '🇹🇷', 'name' => array( 'en' => 'Turkey', 'de' => 'Türkei' ) ),
	array( 'code' => 'UA', 'dial' => '+380', 'flag' => '🇺🇦', 'name' => array( 'en' => 'Ukraine', 'de' => 'Ukraine' ) ),
	array( 'code' => 'AE', 'dial' => '+971', 'flag' => '🇦🇪', 'name' => array( 'en' => 'United Arab Emirates', 'de' => 'Vereinigte Arabische Emirate' ) ),
	array( 'code' => 'GB', 'dial' => '+44', 'flag' => '🇬🇧', 'name' => array( 'en' => 'United Kingdom', 'de' => 'Vereinigtes Königreich' ) ),
	array( 'code' => 'US', 'dial' => '+1', 'flag' => '🇺🇸', 'name' => array( 'en' => 'United States', 'de' => 'Vereinigte Staaten' ) ),
	array( 'code' => 'UY', 'dial' => '+598', 'flag' => '🇺🇾', 'name' => array( 'en' => 'Uruguay', 'de' => 'Uruguay' ) ),
	array( 'code' => 'UZ', 'dial' => '+998', 'flag' => '🇺🇿', 'name' => array( 'en' => 'Uzbekistan', 'de' => 'Usbekistan' ) ),
	array( 'code' => 'VE', 'dial' => '+58', 'flag' => '🇻🇪', 'name' => array( 'en' => 'Venezuela', 'de' => 'Venezuela' ) ),
	array( 'code' => 'VN', 'dial' => '+84', 'flag' => '🇻🇳', 'name' => array( 'en' => 'Vietnam', 'de' => 'Vietnam' ) ),
	array( 'code' => 'YE', 'dial' => '+967', 'flag' => '🇾🇪', 'name' => array( 'en' => 'Yemen', 'de' => 'Jemen' ) ),
);
